more semantic token colors
s1e2b3i4/onenord-vscode pull request #2
Opened 2023-08-23 01:44 UTC by xiyaowong

2023-08-26 10:58 UTC, s1e2b3i4 requested changes
Hey @xiyaowong, thank you for your contribution!
The only thing I would like to change is `"class": "#EBCB8B"`. The reason for that is, that I would like to have the declaration of a class colored differently than the instantiation of it. Therefore, I already set `"class.declaration": "#EBCB8B"`.
What one could do is set the `class` to the color of a function call. But this would then color all class occurrences in that color, and not only the instantiations. And hence I try to be in line with the original theme, this would look not similar anymore.
Besides that, everything looks great and I would merge the PR.

2023-08-26 10:58 UTC, s1e2b3i4 commented on themes/OneNord-color-theme.json
> +      "class": "#EBCB8B",
```suggestion
```

2023-08-29 15:44 UTC, xiyaowong commented
Done~

2023-08-29 19:37 UTC, s1e2b3i4 approved these changes

2023-08-29 19:38 UTC, s1e2b3i4 commented
Thanks for your understanding and your contribution!

2023-08-29 19:38 UTC, closed without merging