chore: minor color adjustements
s1e2b3i4/onenord-vscode pull request #22
Opened 2023-12-14 14:23 UTC by Uaitt

In this PR I have just renamed a few color labels that were misleading. I have not changed a single color value.

Specifically:
- `GREEN_LIGHT` as become `CYAN_LIGHT` 
- `GREEN_LIME` as become `GREEN_LIGHT`
- `PURPLE_DARK` as become `MAGENTA_DARK`
- `PURPLE_LIGHT` as become `MAGENTA_LIGHT`
- ANSI colours from 9 to 13 were removed because they are exactly the same as colours  1 to 5

If you are in doubt about why I did this, please look at the colours visually. You will see why 😄

2024-01-09 17:57 UTC, s1e2b3i4 commented
Yeah, the colors are a little bit messy at the moment 😅 
The only thing I would criticize is the removal of the remaining ANSI-Colors. You are right that they are the same, but it was intentional from me to leave them in. I thought that this would make it more obvious that these colors can be changed, if someone wants to use the bright ANSI-Colors.
Besides that, I would approve this PR 😄

2024-01-09 18:00 UTC, s1e2b3i4 requested changes

2024-01-09 18:00 UTC, s1e2b3i4 commented on src/one-nord.yml
> -    - &COLOR15       '#ECEFF4'
I would leave these colors as they were before.

2024-01-18 13:46 UTC, Uaitt commented on src/one-nord.yml
> -    - &COLOR15       '#ECEFF4'
Yep - fixed!

2024-05-28 11:53 UTC, closed without merging